### ISSUE TITLE
Support PowerShell for 'look' command

### ISSUE THREAD

**Issue by glucas** [motemen/ghq#103]
On Windows the 'look' command uses COMSPEC so it will start a cmd.exe shell. If the user is working in a PowerShell shell this is not what they'd want to do. 

I expected it just to 'cd', but starting a new shell makes sense. Could there be a way to override this by checking for a GHQ_SHELL variable before checking COMSPEC?

**Comment by Songmu** [comment]
Did you know how to get the absolute path of powershell.exe from Go in an existing way? For example, is there any way to access PSHOME variables, etc?

**Comment by Songmu** [comment]
After the #134 merged, we can specify powershell path in SHELL environmant variable.

**Comment by glucas** [comment]
Great, thanks!  

Yes, I think checking some variable the user can override makes sense. Not sure otherwise how you would find the parent shell from within the go process.

**Comment by glucas** [comment]
Tested on 0.11.0 and this works great - thanks again.
