### ISSUE TITLE
Git clone should be able to respect `insteadOf` configuration

### ISSUE THREAD

**Issue by thefotios** [motemen/ghq#109]
I'm currently using [insteadOf](https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf) to alias my company's gitlab instance and force SSH like this:

```ini
[url "git@gitlab.mycompany:"]
        insteadOf = gl:
        insteadOf = ssh://gl/
        insteadOf = https://gl/
```

This mostly works when using `ghq`, except that the directory name is created before running `git ls-remote`. 

Actual/Expected output shown in the diff below:
```diff
$ ghq get gl:foo/bar
clone ssh://gl/foo/bar -> /Users/fotios/src/gl/foo/bar
git clone ssh://gl/foo/bar /Users/fotios/src/gl/foo/bar
- Cloning into '/Users/fotios/src/gl/foo/bar'
+ Cloning into '/Users/fotios/src/gitlab.mycompany/foo/bar' 
```

This can also be used instead to augment specifying `-p` since `insteadOf` can be used to force HTTPS/SSH depending on the path.

**Comment by Songmu** [comment]
I see it is the reverse lookup function. It is considerable feature but, In any case, I think that it should not be the default behavior.

**Comment by Songmu** [comment]
The feature of ghq is that it is easily cloned to the directory corresponding to the argument, so I think that the function of switching the clone destination by looking at the "insteadOf" is unnecessary.
