### ISSUE TITLE
ghq.root should be able to be specified on a per URL basis

### ISSUE THREAD

**Issue by thefotios** [motemen/ghq#110]
If we're using conditional includes in the global gitconfig [(like this example)](https://www.motowilliams.com/conditional-includes-for-git-config), any `git` commands run in different directories may have invalid responses.

It would be very useful if (in conjunction with #109) you could specify a the `git.root` inside the VCS config block and then use that to `cd` before any other commands.

Example:
```ini
# .gitconfig-work
[url "git@gitlab.mycompany:"]
  insteadOf = gl:
  insteadOf = ssh://gl/
  insteadOf = https://gl/
```
```ini
# .gitconfig
[includeIf "gitdir:~/code/work/"]
  path = .gitconfig-work

[ghq "gl:"]
  root = ~/code/work
```

**Comment by Songmu** [comment]
Implemented at #228 and released as v0.17.0.
Try it. Thanks!
