### ISSUE TITLE
homebrew-core can't take in ghq v0.9.0

### ISSUE THREAD

**Issue by kagemiku** [motemen/ghq#111]
**Homebrew/homebrew-core** repository can't take in ghq v0.9.0 because v0.9.0 is not the latest release:
* https://github.com/Homebrew/homebrew-core/pull/34462#issuecomment-441563742

Could you make v0.9.0 release?

**Comment by igas** [comment]
Hi there,

apart from marking the release we would also need dependency management either [modules](https://golang.org/cmd/go/#hdr-Modules__module_versions__and_more) or [dep](https://golang.github.io/dep/)

**Comment by equal-l2** [comment]
@motemen Would you take a look at this?
This issue prevents us from updating the formula for over a month.

**Comment by Songmu** [comment]
I sent pull request for v0.10.0.

https://github.com/Homebrew/homebrew-core/pull/39384

**Comment by Songmu** [comment]
It has been merged. Please use it. Although 0.9.0 has been skipped, please forgive.
