### ISSUE TITLE
0.10.2 Windows zips do not have ghq.exe

### ISSUE THREAD

**Issue by glucas** [motemen/ghq#138]
Trying out the new release and in the Windows amd64/386 zips there is no ghq.exe file. Renaming the file (ghq -> ghq.exe) seems to work fine.

**Comment by Songmu** [comment]
Thank you very much for the report. This was an issue of the goxz I am using for the release. It corresponded in the following pull request.

https://github.com/Songmu/goxz/pull/16

Using new goxz I released ghq v0.11.0 and this problem has been fixed.

Please try v0.11.0.

**Comment by glucas** [comment]
Looks good, thanks!

I'm installing via [scoop](https://scoop.sh) and the ghq manifest there is a bit out of date as there is now a new parent folder in the zip. I'll create a PR to fix this on the scoop side for 0.11.0.
