### ISSUE TITLE
`ghq` does not work well with multiple ghq.root with nonexistent directory

### ISSUE THREAD

**Issue by znz** [motemen/ghq#165]
Recent ghq does not work with multiple ghq.root with nonexistent directory.

I use first ghq.root only. Second ghq.root for `ghq list` after I use `go get`.

I don't know which ghq version does not work.
At least, old ghq works well.

environment:
macOS Mojave and install ghq using homebrew

```
% sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.4
BuildVersion:	18E226
% brew info ghq
ghq: stable 0.12.1 (bottled)
Remote repository management made easy
https://github.com/motemen/ghq
/usr/local/Cellar/ghq/0.12.1 (7 files, 8.0MB) *
  Poured from bottle on 2019-05-08 at 21:37:47
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ghq.rb
==> Dependencies
Build: go ✘
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 2,103 (30 days), 2,943 (90 days), 6,643 (365 days)
install_on_request: 1,940 (30 days), 2,771 (90 days), 6,406 (365 days)
build_error: 0 (30 days)
% git config --get-all ghq.root
/Users/kazu/s
/Users/kazu/g/src
% ghq --version
ghq version 0.12.1 (rev:)
```

expected:
`ghq get https://github.com/motemen/ghq` clone to `~/s/github.com/motemen/ghq`.

actual:
```
% ghq get https://github.com/motemen/ghq
     error lstat /Users/kazu/g/src: no such file or directory
```

I found `ghq list` does not work too.

```
%  ghq list
     error failed to filter repos while walkLocalRepositories(repo): lstat /Users/kazu/g/src: no such file or directory
```

**Comment by Songmu** [comment]
This behavior changed after #60 is merged.

I made this change because I thought it would be better to raise the error clearer than to ignore if the directory doesn't exist.

However, it may be better to create automatically when we `ghq get`. Even in the case of `ghq list`, it is possible to specify a relative path such as ./vendor in GHQ_ROOT, so it may be better not to raise an error after listing the primary root.

**Comment by znz** [comment]
Thank you for your explanation.
I understand changing behavior.
So I create the directory or unset nonexistent directory from ghq.root.
