### ISSUE TITLE
Installation does not complete on Ubuntu 19.04

### ISSUE THREAD

**Issue by jedipunkz** [motemen/ghq#166]
Installation with 'go get' does not complete on Ubuntu Server 19.04.

My environments are ...

```bash
$ go version
go version go1.10.4 linux/amd64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.04
Release:        19.04
Codename:       disco
```

This is how to install ghq with 'go get'

```bash
go get github.com/motemen/ghq
# github.com/motemen/ghq
go/src/github.com/motemen/ghq/local_repository.go:265:19: undefined: os.UserHomeDir
```

Anyidea do you have?

**Comment by nasa9084** [comment]
since v0.10.0, ghq is using os.UserHomeDir which is introduced at Go 1.12 so you cannot build newest ghq with Go 1.10.
if you want to install with `go get`, you need to update Go to 1.12.
or if you do not mind, you can download pre-built binary from releases page.

**Comment by jedipunkz** [comment]
Thanks for you notify.
I downloaded built-binary and got it worked perfectly.
