### ISSUE TITLE
can't set multi ghq.root.

### ISSUE THREAD

**Issue by ryosebach** [motemen/ghq#177]
i set ghq.root in `.gitconfig`, but ghq don't work..

my gitconfig is as follows.

```.gitconfig
[ghq]
	root = ~/dev/src
	root = ~/.go/src
```

i execute `ghq root --all`command, `~/dev/src` is obtained....

Please tell me how to work correctly.

**Comment by Songmu** [comment]
Thanks for registering the issue.

Could you report `ghq --version` and `git --version` ?

**Comment by ryosebach** [comment]
@Songmu 
Thank you for your reply.

```
git version 2.20.1 (Apple Git-117)
ghq version 0.12.3 (rev:)
```

**Comment by Songmu** [comment]
Okay.

Can you report the output of the follwoing command?

```
git config --get-all --path ghq.root
```

**Comment by ryosebach** [comment]
thanks.

i got all of roots :) 

```
~/dev/src
~/.go/src
```

but in executing `ghq root --all` or `ghq list`, i couldn't get directories in `~/.go/src`.

**Comment by moriakijp** [comment]
Try using `$HOME` instead of `~`.

**Comment by moriakijp** [comment]
Have you tried `$HOME` instead of `~` ?

**Comment by Songmu** [comment]
I am in trouble without reproducing the problem at my local. By the way, what happens with ghq 0.12.2?

**Comment by ryosebach** [comment]
wow... already, now i cant get..

I executed command in macOS Mojave 10.14.

```
$ ghq -v
ghq version 0.12.2 (rev:6b231e0)

$ ghq root --all
/Users/xxxxx/dev/src
```

```
$ ghq  -v
ghq version 0.12.4 (rev:HEAD)

$ ghq root --all
/Users/xxxx/dev/src
```

**Comment by Shougo** [comment]
I have tested it in ghq 0.12.6.
But I don't reproduce the problem.

**Comment by Songmu** [comment]
Since the problem cannot be reproduced, I close the issue for now.
