### ISSUE TITLE
How to clone submodules in a repository?

### ISSUE THREAD

**Issue by rnakato** [motemen/ghq#183]
Hi,
I'd like to clone some repository containing submodules.
With git, submodules can be cloned by `git clone --recursive`.
But `ghq get` does not look to have `--recursive` option.
How to clone submodules in a repository?

**Comment by Songmu** [comment]
We can do "submodule update --init --recursive" in each repository for now.

Certainly, since there is a "--shallow" option in `ghq`, it should be useful also to support "--recursive" option as well.

I may implement when I have time, and your patches are also welcome.

**Comment by rnakato** [comment]
Thank you for the reply. I'm looking forward to the update.
