### ISSUE TITLE
Feature request: Remove/delete a repo

### ISSUE THREAD

**Issue by singularitti** [motemen/ghq#184]
Please enable us to remove/delete a cloned repo through `ghq`. Currently, I have to delete them manually. And if possible, I want to be able to remove an organization like `github.com`, or an account under that organization, like `github.com/singularitti/`. Thank you!

**Comment by singularitti** [comment]
A possible command could be `ghq remove [arguments...]`.

**Comment by Songmu** [comment]
You can pass a query argument to `ghq list` like following.

```
ghq list --full-path github.com/motemen
/Users/songmu/dev/src/github.com/motemen/Class-Accessor-Lite-Lazy
/Users/songmu/dev/src/github.com/motemen/blogsync
/Users/songmu/dev/src/github.com/motemen/ghq
...
```

And you can remove them as follows.


```
ghq list --full-path github.com/motemen | xargs rm -r
```

And more, you can use the `--exact`option and some query patterns to list repository paths in various ways.

Is this not enough?

**Comment by singularitti** [comment]
@Songmu Thank you for your reply. I know I can do this by, for example, `rm -rf` or `[trash](https://github.com/sindresorhus/trash)` commands. And I understand this may not be your first priority. But I guess people would be grateful if they can remove something in the same way they create it. That is, what I think, a repository management tool would provide.

**Comment by Songmu** [comment]
After all, I do not feel much need, so close the issue.

In my opinion, it is better to enhance the "ghq list" to easily obtain arbitrary information and delete them by the user in any way.

First, I think that "ghq list" should be enhanced before implementing "ghq remove".

Of course, ghq is OSS, so your patches are also welcome.
