### ISSUE TITLE
`ghq list` is slow when there're lots of repos in ~/.ghq

### ISSUE THREAD

**Issue by gfx** [motemen/ghq#188]
Thanks for developing the excellent tool. I can't do anything without `ghq`!

BTW I have experienced a little trouble about `ghq list`, which takes seconds on my laptop (macOS 10.14.6).

Details:

```shell-session
$ ghq -v
ghq version 0.12.6 (rev:f75cda1)

# 1st time
$ time ghq list > /dev/null
ghq list > /dev/null  0.39s user 1.67s system 83% cpu 2.470 total

# 2nd time
$ time ghq list > /dev/null
ghq list > /dev/null  0.26s user 0.67s system 112% cpu 0.832 total

# count the number of repos
$ ghq list | wc -l
318
```

I think it can get faster because zsh file glob is much faster than `ghq list`, even though zsh does not check anything about repository metadata:

```shell-session
$ time zsh -c 'ls -d ~/.ghq/*/*/*/.git > /dev/null'
0.01s user 0.02s system 74% cpu 0.042 total
```

**Comment by Songmu** [comment]
I recognized this issue and that it will be slow especially on mac.

I don't want to have a complicated file cache mechanism, but I'm thinking of a mechanism that if a process such as "ghq watch" is running, "ghq list" queries to it to get the list.

**Comment by Songmu** [comment]
I close it, because the latest version is fast enough.

Please report if there are any performance issues again.
