### ISSUE TITLE
Feature request: root select option

### ISSUE THREAD

**Issue by taxio** [motemen/ghq#200]
In software engineering (academic), this tool is very useful because researchers collect repositories to analyze.

However, our datasets may be confused because the primary root is always used when `ghq get`.

Currently, I temporarily edit my gitconfig to avoid this problem.

So, I want the option to select root with `ghq get` and `ghq import`.

Of course, I know that it will affect the search algorithm for existing repositories, but would you please consider it?

**Comment by Songmu** [comment]
Thank you for the issue. I understand the problem.

Since `ghq` is a tool that provides "unified" clone rules, we should be careful if implementing this option or not.

For the time being, there are ways to switch settings using the GIT_CONFIG environment variable, "include" option, etc. So could you try it?

**Comment by taxio** [comment]
Thank you @Songmu !!

The “include” option is new to me!!
By using this and handling with gitconfig, I can achieve the behavior what I really want to without editing it each time.

But, I found an easier way.
As shown in the [README](https://github.com/motemen/ghq/tree/fe5ca0511e4d028be926215d05590638e3995c99#environment-variables) and [here](https://github.com/motemen/ghq/blob/fe5ca0511e/local_repository.go#L284-L293), setting the environment variable `GHQ_ROOT` makes it easy to overwrite root because gitconfig not loaded.

Thank you!!

**Comment by Songmu** [comment]
Oh, I forgot the existence of `GHQ_ROOT`. I'm glad that the problem solved.

**Comment by molleweide** [comment]
> Since `ghq` is a tool that provides "unified" clone rules, we should be careful if implementing this option or not.

Hi Songmu, would you mind expanding on why this is problematic?

> The “include” option is new to me!!
> By using this and handling with gitconfig, I can achieve the behavior what I really want to without editing it each time.

Hi Taxio, could you please show me how you managed to use/select multiple roots? Personally, I would like to
clone all of my neovim plugins to one single location.
