### ISSUE TITLE
Suggestion: Make new configure file instead of git-config

### ISSUE THREAD

**Issue by makimoto** [motemen/ghq#21]
Hi, @motemen,

Now ghq's configuration gets complex.
Currently ghq's configuration rents a space from git-config, but I think that it's a time to make the configuration file for ghq.

Have you thought about separating ghq configuration from git-config to another configuration file? (`$HOME/.ghqconfig` or something)

**Comment by josephholsten** [comment]
If you do this, please use `$XDG_CONFIG_HOME` and https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.

**Comment by Songmu** [comment]
The "ghq" depends heavily on git, so I think it would be good to continue using gitconfig. I don't intend to add any more settings.
