### ISSUE TITLE
`ghq get` does not clone to the primary root set in gitconfig

### ISSUE THREAD

**Issue by taxio** [motemen/ghq#239]
## environment

- Mac OS Catalina 10.15.2
- go1.13.5
- ghq v0.17.2

my gitconfig

```
[ghq]
	root = ~/.ghq
	root = ~/go/src
```

`ghq root` returns `~/.ghq` correctly, but when `ghq get <repo>`, it is cloned to `~/go/src`

## I think...
Until v0.16.0, the first path was extracted after getting all with `gitconfig.PathAll("ghq.root")`.

https://github.com/motemen/ghq/blob/aeacda0267/local_repository.go#L99

https://github.com/motemen/ghq/blob/aeacda0267/local_repository.go#L343-L349

https://github.com/motemen/ghq/blob/aeacda026785e37a6f076fdc2f71b5d8153f49fa/local_repository.go#L310

But, since v0.17.0, that has been replaced by `gitconfig.Do("--path", "--get-urlmatch", "ghq.root", remoteURL.String())` .

https://github.com/motemen/ghq/blob/bb059e45e7/local_repository.go#L99

https://github.com/motemen/ghq/blob/bb059e45e72c30b28e38fbadbda29dca71f8d04a/local_repository.go#L114

As a result of attaching the debugger, `gitconfig.Do(...)` returned the second root.
Is this a bug?

**Comment by Songmu** [comment]
Thank you for detailed report.

Certainly, this is an unintended incompatible change.  However, this may be more natural for gitconfig, so I'm not sure should I restore the behavior.

**Comment by taxio** [comment]
thanks.

I think so too. It is more natural to see the last root as primary from the point of view of gitconfig operation.

If so, why not change the behavior of `ghq root`?
This shows the first root yet.

**Comment by Songmu** [comment]
If this incompatible behavior to be true, ghq root must be changed.  This is just my omission.

**Comment by Songmu** [comment]
The behavior has been adjusted in v0.17.3. Now, the last ghq.root setting is the primary directory to clone a repository.

Sorry to trouble you to rewrite the settings.

**Comment by taxio** [comment]
I think this is a great decision.

thank you.

**Comment by Songmu** [comment]
Thanks to your polite report, this problem was solved quickly. Thank you very much.
