### ISSUE TITLE
remove "look" subcommand

### ISSUE THREAD

**Issue by Songmu** [motemen/ghq#241]
We can substitute `ghq look` with the following command.

```console
% ghq get --look motemen/ghq
```

Also, this "look" function is for temporarily looking at the contents of the repository, and is not suitable for changing the working directory.

This is because the "look" function creates a child process, which needs to be exited with the exit command. This causes non-intuitive behavior.

For switching the working directory, it is recommended to just "cd".

```console
% cd $(ghq list --full-path --exact motemen/ghq)
```

**Comment by snowman** [comment]
`alias ghqq='cd $(ghq list -full-path --exact $(ghq list | sed "s:[^/]*/::" | percol))'`
