### ISSUE TITLE
Update detect GitHub username function

### ISSUE THREAD

**Issue by tomato3713** [motemen/ghq#253]
`ghq create` is very good subcommand!

When I creating a new repository with `ghq create`, $USER was used for GitHub username.
because of ghq.user was not set.
Currently, the user name is obtained in the following order.
1.ghq.user
2. GitHub username
3. $USER or $USERNAME

However, if one or two are not found, it seems natural to use the name set in `git config user.name ${GIT_USERNAME}`.

How about that?

**Comment by Songmu** [comment]
Thanks for the suggestion.

Actually, I have thought that it might be good. However, I rejected this idea.

Because, `git config user.name` is generally a full name and often contains spaces and user names in ghq are like unix login names, full names are not appropriate.

**Comment by tomato3713** [comment]
Ok. I understood why use $USER, not `git config user.name`. 
thank for reviewing.
