### ISSUE TITLE
ghq 1.0.2 shows nothing in Windows

### ISSUE THREAD

**Issue by kai2nenobu** [motemen/ghq#272]
I download [version 1.0.2 for windows](https://github.com/motemen/ghq/releases/download/v1.0.2/ghq_windows_amd64.zip), but `ghq.exe` shows nothing in command prompt as below.

```console
> ghq.exe --version

> ghq.exe root

> ghq.exe list

```

Curiously enough, `ghq.exe` with pipe shows output as below.

```console
> ghq.exe --version | more
ghq version 1.0.2 (rev:3981090)


> ghq.exe root | more
C:\Users\kai2nenobu\ghq


> ghq.exe list | more
github.com/junegunn/fzf
github.com/motemen/ghq


```

I noticed that every time I run `ghq.exe`, another (command prompt?) window opened only for a moment and closed immediately.

My Environment

```
OS: Windows 10 Pro
Version: 1909
Build: 18363.592
```

**Comment by mattn** [comment]
What output you get with `where ghq` ?

**Comment by kai2nenobu** [comment]
> 
> 
> What output you get with `where ghq` ?

`ghq` is not in PATH and I run `ghq` in `C:\Users\kai2nenobu\Downloads\ghq_windows_amd64` (directory where I extracted `ghq_windows_amd64.zip`). So `where ghq` output as below.

```console
> where ghq
INFO: Could not find files for the given pattern(s).

> cd C:\Users\kai2nenobu\Downloads\ghq_windows_amd64

> where ghq
C:\Users\kai2nenobu\Downloads\ghq_windows_amd64\ghq.exe

```

**Comment by mattn** [comment]
BTW, what is your CPU architecture? i386 ?

**Comment by kai2nenobu** [comment]
> 
> 
> BTW, what is your CPU architecture? i386 ?

No, x86_64 (Intel Core i5 6260U).

**Comment by mattn** [comment]
Hmm, it have no idea... What do you get with:

```
cd C:\Users\kai2nenobu\Downloads\ghq_windows_amd64
call ghq
```

**Comment by kai2nenobu** [comment]
`call ghq` output nothing.

```console
> cd C:\Users\kai2nenobu\Downloads\ghq_windows_amd64

> call ghq

```

`call ghq --version` or `call ghq list` also output nothing. It seems to be same as executing without `call`.

**Comment by mattn** [comment]
I figured out what caused by this issue now. I'll send pull-request to goxz.

**Comment by mattn** [comment]
https://github.com/Songmu/goxz/pull/21

**Comment by Songmu** [comment]
The fixed version was released as 1.0.3.

There is also a problem of license credit at the time of distribution then, I stopped the static build and set CGO_ENABLED to 0 for building "go" only binary executable.

**Comment by mattn** [comment]
👍 


![image](https://user-images.githubusercontent.com/10111/72865603-d24e9c80-3d1b-11ea-8853-a48dfbc6dbf1.png)

**Comment by kai2nenobu** [comment]
Works as I expected. Thanks for quick fix :+1:

![image](https://user-images.githubusercontent.com/810042/72892023-e4026500-3d58-11ea-8e89-d59c4f8981fb.png)
