### ISSUE TITLE
`ghq list` does not return anything.

### ISSUE THREAD

**Issue by shunkakinoki** [motemen/ghq#274]
I upgraded to ghq version 1.0.3. and the `ghq list` started showing zero repos.

I'm on mac on Catalina!

**Comment by Songmu** [comment]
Since v0.99.0, the default value of ghq.root has been changed from `~/.ghq` to` ~/ghq`. Are there any effects of this change?

In that case, please try the following command.

```console
mv ~/.ghq ~/ghq
```

**Comment by shunkakinoki** [comment]
thanks for the quick response!

aha. problem solved!

Really appreciate and love your work @Songmu

**Comment by tikidunpon** [comment]
If `.git` directory exists under `~/ghq`, `ghq list` will only return one dot.
I know this is an edge case, but I'm commenting on it because it might be useful to someone else..
