### ISSUE TITLE
ghq should drop the port from the folder name

### ISSUE THREAD

**Issue by siancu** [motemen/ghq#50]
Some of the projects I work on are stored in private git repos where the SSH daemon is listening to a custom port. When using ghq, I noticed that the folder created by ghq contains :\<port_number\> which is not desirable IMO.

**Comment by motemen** [comment]
Thank you for the feedback.

I want ghq to follow how `go get` makes folders, which does not seems to replace `:<port>`s. So I am not thinking of dropping or rewriting port numbers in URLs.

As a workaround, you can use `url.insteadOf` Git configuration to avoid port numbers in directories. For example:

~~~gitconfig
# ~/.gitconfig
[url "ssh://git@github.com:22/"]
    insteadOf = ssh://gh/
~~~

You can run `ghq get ssh://gh/motemen/ghq` to clone from GitHub and ghq creates `gh/motemen/ghq` directory.

cf: https://github.com/motemen/ghq/pull/26#issuecomment-50594051

**Comment by tikkss** [comment]
Thank you @motemen !!!
