### ISSUE TITLE
Feature request: accept url as a query for `ghq list`

### ISSUE THREAD

**Issue by kergoth** [motemen/ghq#52]
While the look command is useful, spawning a new shell is less than ideal for scripting, so a sub-command which simply returns the path on disk would be useful.

**Comment by motemen** [comment]
Thank you for the feedback, how about using `ghq list --exact --full-path` (`ghq list -e -p`) ?

**Comment by kergoth** [comment]
That does seem close. What about also accepting the upstream url as a query for list, much as was recently added to `ghq look`?

**Comment by motemen** [comment]
Got the point, let's get it implemented.
