### ISSUE TITLE
Feature request: add ability to also specify vcs as an argument to `ghq get`

### ISSUE THREAD

**Issue by kergoth** [motemen/ghq#53]
Given that we can force the vcs in the gitconfig, it'd be nice to be able to specify it on the `ghq get` command-line and have it automatically store that information in gitconfig for us. That was the first place I looked when wanting to explicitly set the vcs, and only found the configuration via re-reading the README.

**Comment by motemen** [comment]
Working on it: https://github.com/motemen/ghq/pull/72
