### ISSUE TITLE
Default value for `ghq.root`

### ISSUE THREAD

**Issue by motemen** [motemen/ghq#60]
Currently `ghq.root` defaults to `~/.ghq`, which seems not convenient very well. Can we have more-suitable default value?

Or showing a prompt to configure `ghq.root` on first startup of `ghq`?

**Comment by motemen** [comment]
As a note, I'm using `~/dev/src` and `~/dev/go/src` (= `"$GOPATH/src"`) for `ghq.root` .

**Comment by pomutemu** [comment]
FYI:

- https://github.com/search?utf8=✓&q=filename%3Agitconfig+"ghq+root"&type=Code
- https://github.com/search?utf8=✓&q=filename%3Agitconfig+"ghq+root+src"&type=Code

**Comment by sona-tar** [comment]
I,m using ′~/src/′

**Comment by kyanny** [comment]
@motemen 
Why do you think `~/.ghq` is not convenient?
If it is because `~/.ghq` is a hidden directory, how about remove dot?
(it means the default value of `ghq.root` becomes `~/ghq`)

Anyway, I'm using `$HOME/Documents`.

**Comment by maoe** [comment]
I've been using `~/src`.

I'm +1 to showing a prompt to configure it on the first startup as I guess the preferences vary from person to person.

**Comment by ress997** [comment]
I'm with the reference to the XDG Base Directory Specification in `$XDG_DATA_HOME/ghq/src`

**Comment by Songmu** [comment]
https://twitter.com/songmu/status/1202199772636909569

**Comment by Songmu** [comment]
I plan to make "~/ghq" the default.
