### ISSUE TITLE
RFC: Support Go 1.3 (undefined: atomic.Value in mitchellh/go-homedir)

### ISSUE THREAD

**Issue by lambdalisue** [motemen/ghq#62]
I'm not really sure which to report this issue but I'm using your *ghq* and not *go-homedir* thus I decide to report the issue here.
Well, when I tried to install this program by `go get github.com/motemen/ghq`, the command fail with

```
../../../.go/src/github.com/mitchellh/go-homedir/homedir.go:18: undefined: atomic.Value
```

It seems that the `atomic.Value` feature was implemented from Go 1.4, and I'm using Go 1.3.3 which is available on Ubuntu 15.04 ([ref](https://github.com/graphite-ng/carbon-relay-ng/issues/73#issuecomment-99446720), the use was implemented in *go-homedir* at [this commit](https://github.com/mitchellh/go-homedir/commit/56f508a88415ab57e596a176f0789ede8f790903))
So I'll be really happy if you decide to support Go 1.3, which can be installed through `apt-get`.

**Comment by syohex** [comment]
`ghq` provides binaries for each platforms, also Linux, from [this page](https://github.com/motemen/ghq/releases). You need not to do `go get` by using binary.

**Comment by lambdalisue** [comment]
Hum... Good point. A disadvantage of using binaries is that you may miss updates of `ghq`, but that it. While I'm stick on using `ghq`, probably I should switch to use binaries instead of HEAD.

Thanks for giving me a direction :smile:

**Comment by motemen** [comment]
Oh, thanks anyway to both! :pray:
