### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by naoyamuto** [motemen/ghq#69]
I'm using `ghq get` command, but there are some errors as below.

```
 error Could not find version control system: https://hogehoge.com/hogehoge
```

How do I do to fix this error?
- using GitHub Enterprise
- using Mac

**Comment by syohex** [comment]
Did you set git config parameter `ghq.<url>.vcs` ?

```
% git config --global ghq.https://hogehoge.com/hogehoge.vcs github
```

See also
- https://github.com/motemen/ghq#configuration
- https://github.com/motemen/ghq/blob/86bb988011f74de81274a6cead9d3e3f65b7f734/remote_repository.go#L138-L141

**Comment by motemen** [comment]
Cannot answer without concrete information:

- The whole command output
- GitHub Enterprise configuration. Was it a repository "hogehoge" hosted on a GitHub Enterprise at hogehoge.com?

By the way, I'm working on a feature which provides `--vcs` option on `get`: #72. I'd be help.
