### ISSUE TITLE
Having "DEPRECATED Action signature." message

### ISSUE THREAD

**Issue by TakaakiFuruse** [motemen/ghq#77]
Currently, I am having following message, whenever I execute ghq related command.  

```
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature
```

It's just because codegangsta/cli a dependent library of ghq was updated.
Do you have any idea how I can get rid of this message?

**Comment by syohex** [comment]
See #76.

**Comment by TakaakiFuruse** [comment]
Thanks @syohex, it was my bad, I should have read issues carefully.
