### ISSUE TITLE
ghq browse to open the project page in a browser

### ISSUE THREAD

**Issue by maoe** [motemen/ghq#79]
It would be handy if ghq could open the project page that corresponds to a repository in a browser. For example:

```
% ghq get -p foo/proj1
% ghq look foo/proj1
% ghq browse  # opens up a browser
```

and/or simply

```
% ghq browse foo/proj1
```

from anywhere outside the repo.

There are a few considerations though:
- Some heuristics may be necessary to identify the project page
- An extra configuration variable in .gitconfig may be preferable to configure the browser to use.

What do you think?

**Comment by Songmu** [comment]
I think the "hub browse" command covers most cases.

This issue has been left for a long time, so I close is once.

You can pull request about it.
