### ISSUE TITLE
`--full-path` option show the relative paths with the relative `root`

### ISSUE THREAD

**Issue by delphinus** [motemen/ghq#80]
1. Set relative paths in `.gitconfig`
   
   ``` sh
   [ghq]
   root = ~/.go/src
   root = ./vendor
   ```
2. Run `ghq list` with `--full-path, -p` option
   
   ``` sh
   $ cd /path/to/some/golang/repo
   $ ghq list -p
   /Users/delphinus/.go/src/github.com/mattn/gom
   /Users/delphinus/.go/src/github.com/mattn/gover
   /Users/delphinus/.go/src/github.com/mattn/goveralls
   
   ...
   
   vendor/github.com/BurntSushi/toml
   vendor/github.com/urfave/cli
   ```

I think the last two paths should be absolute, such as...

``` sh
/path/to/some/golang/repo/vendor/github.com/BurntSushi/toml
/path/to/some/golang/repo/vendor/github.com/urfave/cli
```

Is it the specification, or the bug?

**Comment by motemen** [comment]
Actually I have not imagined setting a relative path to `ghq.root`. Should be counted as a bug.

**Comment by delphinus** [comment]
When I manage package dependencies in golang projects, I usually use package manager such as gom, glide,... that will clone packages below `/path/to/projects/vendor` directory.

I noticed this bug when I use [unite-ghq][] (my self-made plugin) for Vim to show up that package dependencies list. I want to show local packages (below `./vendor/github.com/...`) with global packages (below `$GOPATH/github.com/...`) by this plugin.

[unite-ghq]: https://github.com/delphinus/unite-ghq

<img width="563" alt="2016-10-05 23 53 18" src="https://cloud.githubusercontent.com/assets/1239245/19118339/13d24bfe-8b57-11e6-9ba3-1b1765eea45d.png">

I can deal with this case by rewriting paths in VimScript, but I would appreciate your fixing this bug.
