### ISSUE TITLE
ghq get and look

### ISSUE THREAD

**Issue by franciscocpg** [motemen/ghq#84]
I'd like to propose a flag to go to the cloned repository just after `get` command.
So instead of running, for example:
```
ghq get git@domain.com:user/project
ghq look git@domain.com:user/project
```
We ran just (supposing this new flag is `-l`)
```
ghq get -l git@domain.com:user/project
```
I can propose a PR for that if convenient.

**Comment by Songmu** [comment]
resolved at #112
