### ISSUE TITLE
Add some kind of transforms for "ghq.<url>." 

### ISSUE THREAD

**Issue by thomasf** [motemen/ghq#86]
Instead of doing this:

```sh
ghq get git@my-repo-server.example.com:20022/group/project.git 
```

I want to do this:

```sh
ghq get my-repo-server.example.com/group/project
```

I'ts similar to what GIT's `url.<base>.pushInsteadOf` does but more powerful
and specifically for GHQ.

## quickly thrown together configuration example

The URL in `[ghq "my-repo-server.example.com/"]` becomes a simple prefix string
matcher which then looks at match/replace to construct the final URLs.

Conceptually it could work something like this but there are probably more use
cases to think about.

```
[ghq "my-repo-server.example.com/"]
  vcs = git
  match = my-repo-server.example.com/(?P<rest>.*)/+
  replace = git@my-repo-server.example.com:20022/${rest}.git
```

Forcefully overriding https with .git:

```
[ghq "https://my-repo-server.example.com/"]
  vcs = git
  match = https://my-repo-server.example.com/(?P<rest>.*)/+
  replace = git@my-repo-server.example.com:20022/${rest}.git
```

And configure sub paths of hosts to be translated where the longest match wins(?):

```
[ghq "github.com/"]
  vcs = git
  match = github.com/(?P<rest>.*)
  replace = https://github.com/{rest}
  
[ghq "github.com/thomasf/"]
  vcs = git
  match = github.com/thomasf/(?P<rest>.*)/+
  replace = git@github.com:thomasf/{rest}.git
```

**Comment by thomasf** [comment]
I also use a LOT of different repository hosts so I would prefer that it was possible to disable `ghq get some/thing` to go directly to github, I would like to get an error instead and only work when qualifying github.com as well: `ghq get github.com/some/thing`.

**Comment by thomasf** [comment]
This would probably make more sense btw, if there is a replace the first string
will be considered a regexp match/capture instead of a plain URL.

```
[ghq "my-repo-server.example.com/(?P<rest>.*)/+"]
	vcs = git
    replace = git@my-repo-server.example.com:20022/${rest}.git
```

But I'm getting ahead of myself with solutions, I would like to know what other people might need from something like this first.

**Comment by thomasf** [comment]
This issue is related to https://github.com/motemen/ghq/issues/21 because this feature would probly benifit alot from a less constrained config format

**Comment by thomasf** [comment]
Ok so `[ghq "my-repo-server.example.com/(?P<rest>.*)/+"]` is not an url and thus unsupported by git config..

Looking at remote_repository code it seems like it shouldnt be very complicated to fit almost everything it does for every back end into some configuration file language.

**Comment by Songmu** [comment]
As a ghq feature, the correspondence between queries and directories is very clear. However, if such complicated rules are applied, it will be difficult to understand, and overkill.

So I close it once.
