### ISSUE TITLE
Feature request: search github for repos and import first result

### ISSUE THREAD

**Issue by blackxored** [motemen/ghq#91]
I understand this would add a significant amount of code to this project, but I think it would be really nice to be able to search Github for a repo and import the first result (maybe after confirmation).

Ex: 
```shell
$ ghq get ghq
```

would search Github for ghq and import this project without having to type:

```shell
$ ghq get motemen/ghq
```

**Comment by Songmu** [comment]
you can do it as follows. 

```console
echo 'ghq' \
  | xargs -I@ curl -s https://api.github.com/search/repositories\?q=@ \
  | jq -r '.items[0].clone_url' \
  | xargs ghq get
```

This is an example using curl, but it would be nice to have another tool that returns the repository URL from the query string.
