### ISSUE TITLE
Feature request: specify vcs argument on `ghq list`

### ISSUE THREAD

**Issue by msh5** [motemen/ghq#94]
It'd be nice to be able to filter working directories by VCS.
This is useful in the case to run git-gc on all local Git repositories.
```
for line in $(ghq list --full-path --vcs=git); do
  git gc --aggressive
done
```

Please tell me your opinions.
If my request be accepted, I will prepare PR to support this feature.

**Comment by Songmu** [comment]
It is an interesting feature, so if you still feel motivated, please try to implement.

**Comment by msh5** [comment]
@Songmu Thanks for your agreement. Now I have a lot of work so I can't start soon but I sure that I'll make PR in nearly future.

**Comment by msh5** [comment]
@Songmu I've created my PR about this issue, please check it. Thanks.

**Comment by Songmu** [comment]
Good job! Thank!
