### ISSUE TITLE
Feature request: fork then clone

### ISSUE THREAD

**Issue by blackxored** [motemen/ghq#96]
git-extras has a fork then clone command that'd be handy to add here as well. 
I realize it would be a bit difficult to make it non Github-specific but I'd be more than happy with just Github support for starters.

EDIT:
`ghq get -f <github_repo` for syntax would be awesome.

**Comment by Songmu** [comment]
We can `hub fork` after `ghq get`.

**Comment by gpaulsen** [comment]
@Songmu - Question - `hub fork` doesn't also setup your remotes to point to your ghq clone does it?   How do you handle that?
